### PR TITLE
Ft client signin/login screen

### PR DESCRIPTION
**Pull request by chidiogo-akunne**
#### What does this PR do?

Ui for client to log in with either their email, facbook or google account

#### Description of Task to be completed?

Have the Login/Sign-in screen show the following:

1. a text showing welcome to the app.
2. An input field where a client can enter an email address.
3. Three buttons

### CODE REVIEW

**Comment by chidiogo-akunne** [comment]
I would have but I don’t have an emulator

**Comment by ogbodo** [comment]
So how did you test it? If you used real device, you can also take a screen shot of it when testing it.

**Comment by chidiogo-akunne** [comment]
I used my phone, yeah I can take a screenshot but how do I upload it?

Note: I'm using an iPhone and working with a windows system

**Comment by ogbodo** [comment]
I believe you have a xender application on your iPhone, you can xender it using the web version connected to your phone. Just google how to do it if you have not done it before, ok.
Or better still check out his link https://techlector.com/use-xender-transfer-files-phones-pc/

**Pull request merged**
